package me.ccampo.nexia.api.client.model

import java.time.Instant
import java.time.LocalDateTime
import java.util.UUID

/**
 * @author ccampo on 2019-06-05
 */
data class Thermostat(
        val id: Long,
        val pin: String,
        val is_setup: Boolean,
        val expires_at: Instant,
        val account_id: Long,
        val house_id: Long,
        val created_at: Instant,
        val updated_at: Instant,
        val auid: String,
        val operating_mode: String,
        val system_code: String,
        val fan_mode: String,
        val current_time: Instant,
        val installation_locked: Boolean,
        val have_odt: Boolean,
        val raw_outdoor_temperature: Int,
        val have_rh: Boolean,
        val raw_relative_humidity: Double,
        val outdoor_state: String,
        val heat_active: Boolean,
        val temperature_deadband: Int,
        val zoning_enabled: Boolean,
        val notified_for_temperature: Any?,
        val temperature_blackout: Any?,
        val temperature_high_limit: Int,
        val temperature_low_limit: Int,
        val system_name: String?,
        val instance_number: Int,
        val blower_active: Boolean,
        val emergency_heat_supported: Boolean,
        val emergency_heat_active: Boolean,
        val name: String,
        val current_relative_humidity: Double,
        val humidify_allowed: Boolean,
        val dehumidify_allowed: Boolean,
        val humidify_setpoint: Double,
        val dehumidify_setpoint: Double,
        val frost_index: Int,
        val dealer_phone_number: String,
        val manufacturer_code: String,
        val dev_build_number: String,
        val firmware_build_name: String,
        val onboard_device_id: Any?,
        val onboard_device_type: String,
        val enrollment_failure: Any?,
        val scale: String,
        val system_guid: UUID,
        val enrolled_at: Instant,
        val smart_optimizer_running: Boolean,
        val demand_response_start: Any?,
        val demand_response_end: Any?,
        val demand_response_status: Any?,
        val last_operating_state: String,
        val occupied_tid: Any?,
        val unoccupied_tid: Any?,
        val fan_speed: Double,
        val min_fan_speed: Double,
        val max_fan_speed: Double,
        val fan_circulation_time: Int,
        val compressor_speed: Any?,
        val requested_compressor_speed: Any?,
        val fan_type: String,
        val has_variable_speed_compressor: Boolean,
        val has_heatpump: Boolean,
        val quiet_mode_enabled: Boolean,
        val last_listened_to_at: Any?,
        val model_number: String,
        val ecofactor_enrolled: Boolean,
        val notified_for_sensor_fault: Boolean,
        val access_level_type: String,
        val pin_enabled: Boolean,
        val pin_passcode: Any?,
        val technican_pin_enabled: Boolean,
        val technican_passcode: String?,
        val system_status: String,
        val outdoor_temperature: String,
        val edge_update_delta: Double,
        val dealer_identifier: String,
        val zones: List<Zone>,
        val stale: Boolean,
        val last_update_time: LocalDateTime,
        val thermostat_type: String,
        val air_cleaner_mode: String,
        val current_timestamp: Long,
        val alert_settings: Map<AlertSettingType, AlertSetting>,
        val type: String,
        val supports_runtime_history: Boolean,
        val hide_monthly_runtime_history: Boolean,
        val show_demand_response: Boolean,
        val demand_response_state: String?,
        val max_schedule_periods: Int
)
